# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Zarko Susnjar'
tagline:          'tech coding blog'
description:      'desription tralalalal'
url:              http://zarkosusnjar.github.io

author:
  name:           'Zarko Susnjar'
  url:            https://facebook.com/zarko.susnjar

paginate:         5

# Custom vars
version:          1.0.0

github:           
  repo:           https://github.com/zarkosusnjar/zarkosusnjar.github.io